### ISSUE TITLE
A small issue with writing mpdecimate_filter into TEMP folder (I think)

### ISSUE THREAD

**Issue by mart-hill** [KenjiTakahashi/mpdecimate_trim#6]
That's the error I'm getting after calling `python .\mpdecimate_trim.py --debug .\2021-04.mp4` :)
```
2023-11-18 20:56:23[I] Standard output capture: w:\Temp\mpdecimate_trim.tfljivxj\decimate.stdout.log
2023-11-18 20:56:23[I] Standard error capture: w:\Temp\mpdecimate_trim.tfljivxj\decimate.stderr.log
2023-11-18 20:56:24[I] The decimate phase took 00:00:01
2023-11-18 20:56:24[I] The filter creation phase is starting
2023-11-18 20:56:24[I] Filter definition: w:\Temp\mpdecimate_trim.tfljivxj\mpdecimate_filter
Traceback (most recent call last):
  File "X:\Videos\decim\mpdecimate_trim.py", line 199, in <module>
    write_filter()
  File "X:\Videos\decim\mpdecimate_trim.py", line 47, in a
    r = f(*args, **kwargs)
  File "X:\Videos\decim\mpdecimate_trim.py", line 181, in write_filter
    frames_to_keep, has_audio = get_frames_to_keep(mpdecimate_fn)
  File "X:\Videos\decim\mpdecimate_trim.py", line 151, in get_frames_to_keep
    for line in mpdecimate:
  File "C:\Users\Mik\AppData\Local\Programs\Python\Python310\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x88 in position 4249: character maps to <undefined>
```
Of course, I'm not launching Python with admin right (Windows 10 22H2).

**Comment by KenjiTakahashi** [comment]
Interesting, looks like there are some file encoding problems on Windows. I've only tested with `en-US` locale, which is the "happy path" usually. I've now pushed an update to force `utf8` encoding for all temp files. Should hopefully fix the problem.
